apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantsbywebsphereee6
  labels:
    app: plantsbywebsphereee6
spec:
  selector:
    matchLabels:
      run: plantsbywebsphereee6
  replicas: 1
  template:
    metadata:
      labels:
        run: plantsbywebsphereee6
    spec:
      containers:
      - name: app
        env:
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: info
        - name: WLP_LOGGING_CONSOLE_SOURCE
          value: message,accessLog,ffdc,audit
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: json
        envFrom:
        - configMapRef:
            name: plantsbywebsphereee6-config
        image: image-registry.openshift-image-registry.svc:5000/dev/pbw
        volumeMounts:
        - mountPath: /config/variables
          name: plantsbywebsphereee6-secret
          readOnly: true
        ports:
        - containerPort: 9080 
      restartPolicy: Always
      volumes:
      - name: plantsbywebsphereee6-secret
        secret:
          defaultMode: 420
          secretName: plantsbywebsphereee6-secret
---
apiVersion: v1
kind: Service
metadata:
  name: plantsbywebsphereee6
  labels:
    app: plantsbywebsphereee6
    run: plantsbywebsphereee6
spec:
  selector:
    run: plantsbywebsphereee6
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: plantsbywebsphereee6
  labels:
    app: plantsbywebsphereee6
    run: plantsbywebsphereee6
spec:
  host: plantsbywebsphereee6-dev.apps.ocp.ibm.edu
  port:
    targetPort: 9080
  to:
    kind: Service
    name: plantsbywebsphereee6
    weight: 100
  wildcardPolicy: None
